### ISSUE TITLE
java 

### ISSUE THREAD

**Issue by alain-andre** [alain-andre/mon_site#4]
`~./bashrc`

``` bash
# Android Dev PATH
export ANDROID_HOME=~/android/Sdk
export PATH=${PATH}:~/android-studio/tools
export PATH=${PATH}:~/android-studio/platform-tools
```

```
$ ionic build android
Running command: /home/alain/01_projets/xxx/mobile/hooks/after_prepare/010_add_platform_class.js /home/alain/01_projets/xxx/mobile
add to body class: platform-android
Running command: /home/alain/01_projets/xxx/mobile/platforms/android/cordova/build 
[Error: Failed to run "java -version", make sure that you have a JDK installed.
You can get it from: http://www.oracle.com/technetwork/java/javase/downloads.
]
ERROR building one of the platforms: Error: /home/alain/01_projets/xxx/mobile/platforms/android/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /home/alain/01_projets/xxx/mobile/platforms/android/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

```
alain@alain-Sys1:/usr/bin$ ls -l | grep java 
lrwxrwxrwx 1 root   root          22 mai   19 08:16 java -> /etc/alternatives/java
alain@alain-Sys1:/usr/bin$ cd /etc/alternatives/
alain@alain-Sys1:/etc/alternatives$ ls -l | grep java 
lrwxrwxrwx 1 root root  46 mai   19 08:16 java -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
lrwxrwxrwx 1 root root  56 mai   19 08:16 java.1.gz -> /usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/java.1.gz
lrwxrwxrwx 1 root root  47 mai   19 08:16 jexec -> /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jexec
lrwxrwxrwx 1 root root  52 mai   19 08:16 jexec-binfmt -> /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jar.binfmt
lrwxrwxrwx 1 root root  45 mai   19 08:16 jjs -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/jjs
lrwxrwxrwx 1 root root  55 mai   19 08:16 jjs.1.gz -> /usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/jjs.1.gz
lrwxrwxrwx 1 root root  49 mai   19 08:16 keytool -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
lrwxrwxrwx 1 root root  59 mai   19 08:16 keytool.1.gz -> /usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/keytool.1.gz
lrwxrwxrwx 1 root root  46 mai   19 08:16 orbd -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/orbd
lrwxrwxrwx 1 root root  56 mai   19 08:16 orbd.1.gz -> /usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/orbd.1.gz
lrwxrwxrwx 1 root root  49 mai   19 08:16 pack200 -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/pack200
lrwxrwxrwx 1 root root  59 mai   19 08:16 pack200.1.gz -> /usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/pack200.1.gz
lrwxrwxrwx 1 root root  52 mai   19 08:16 policytool -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/policytool
lrwxrwxrwx 1 root root  62 mai   19 08:16 policytool.1.gz -> /usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/policytool.1.gz
lrwxrwxrwx 1 root root  46 mai   19 08:16 rmid -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmid
lrwxrwxrwx 1 root root  56 mai   19 08:16 rmid.1.gz -> /usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/rmid.1.gz
lrwxrwxrwx 1 root root  53 mai   19 08:16 rmiregistry -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmiregistry
lrwxrwxrwx 1 root root  63 mai   19 08:16 rmiregistry.1.gz -> /usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/rmiregistry.1.gz
lrwxrwxrwx 1 root root  52 mai   19 08:16 servertool -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/servertool
lrwxrwxrwx 1 root root  62 mai   19 08:16 servertool.1.gz -> /usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/servertool.1.gz
lrwxrwxrwx 1 root root  51 mai   19 08:16 tnameserv -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/tnameserv
lrwxrwxrwx 1 root root  61 mai   19 08:16 tnameserv.1.gz -> /usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/tnameserv.1.gz
lrwxrwxrwx 1 root root  51 mai   19 08:16 unpack200 -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/unpack200
lrwxrwxrwx 1 root root  61 mai   19 08:16 unpack200.1.gz -> /usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/unpack200.1.gz
alain@alain-Sys1:/etc/alternatives$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

Modifi du bashrc : 

```
# Android Dev PATH
export JAVA_HOME=/usr/bin/java
```

`$ source ~/.bashrc`

```
$ ionic build android
Running command: /home/alain/01_projets/xxx/mobile/hooks/after_prepare/010_add_platform_class.js /home/alain/01_projets/xxx/mobile
add to body class: platform-android
Running command: /home/alain/01_projets/xxx/mobile/platforms/android/cordova/build 
[Error: Failed to run "java -version", make sure that you have a JDK installed.
You can get it from: http://www.oracle.com/technetwork/java/javase/downloads.
Your JAVA_HOME is invalid: /usr/bin/java
]
ERROR building one of the platforms: Error: /home/alain/01_projets/xxx/mobile/platforms/android/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /home/alain/01_projets/xxx/mobile/platforms/android/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by alain-andre** [comment]
apt-get install openjdk-8-jdk
